# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9e63c41477d45ae23acc95e1664d64d4f31cd6fa34f3d51b174a62c6b7ddb705fe53ce1fefcacf3ad89c9d459e2e2d4ed799f3544149363df0ee58bc0aa236

test:
  secret_key_base: ab727c5dc543ec50c0bc3b75d9699493073ade029bc5bf25838703402d3c907443aeda46f431c7b1e758c87dab29f1e0f3edaf4ff597cccf0a4afa4faee3e023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
